import type { NextPage } from 'next'
import Head from 'next/head'
import { dehydrate, QueryClient } from "react-query";
import { getData } from "../uttils/fetchApi";
import HomePageContainer from "../containers/HomePageContainer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/src/public/favicon.ico" />
      </Head>

      <HomePageContainer />

    </div>
  )
}

export async function getServerSideProps(ctx: any) {
  const { page } = ctx.query
  const queryClient = new QueryClient()
  await queryClient.prefetchQuery(["getAllNews", {
      page: page ? page : 1,
      limit: 4,
    }],
    getData
  )

  return {
    props: {
      dehydratedState: dehydrate(queryClient)
    },
  }
}


export default Home
